name: npm install
description: npm install
inputs:
  ls_options:
    description: ls options
    required: false
    # in windows, la does NOT work
    default: "-la"

runs:
  using: composite
  steps:
    - name: npm run setup:ci
      shell: bash
      run: npm run setup:ci --if-present

    - name: npm install
      shell: bash
      run: npm ci

    - name: ls
      shell: bash
      run: ls ${{ inputs.ls_options }} ./node_modules
