name: npm run lint
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  npm_run_lint:
    name: npm run lint
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-reusable-workflows/.github/actions/checkout@main
      - uses: percebus/github-reusable-workflows-node/.github/actions/node_setup@main
      - uses: ./.github/actions/npm_install

      - name: npm run lint
        run: npm run lint
